### ISSUE TITLE
.iemod contains full source for iconv

### ISSUE THREAD

**Issue by mleduque** [Pocket-Plane-Group/Turnabout#3]
Surprised by the size difference between the `lin-turnabout-v1.8.zip` (2,82M) and the `turnabout-v1.8.iemod ` (8,05M), I went to check for the difference (I expected the .iemod to contain the weidu EXE but it didn't).

It ends up being iconv, fair.

But then, it's not the exe and the dll that take up all that space, it's `tra/iconv/libicon-1.9.2-1-src.zip` which is (my guess) the source tarball for libiconv.

Is it needed at installation time?

**Comment by Gitjas** [comment]
This iconv zip is not needed for running the installation, it's in for the licence. Linux has its own iconv so the mod package intended for it doesn't contain the iconv zip. I hope this answers the question.

**Comment by mleduque** [comment]
Ah yes that's a LGPL requirement, sorry.
